// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wechat.proto

package wechatpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetMediaListRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMediaListRequest) Reset()         { *m = GetMediaListRequest{} }
func (m *GetMediaListRequest) String() string { return proto.CompactTextString(m) }
func (*GetMediaListRequest) ProtoMessage()    {}
func (*GetMediaListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{0}
}

func (m *GetMediaListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMediaListRequest.Unmarshal(m, b)
}
func (m *GetMediaListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMediaListRequest.Marshal(b, m, deterministic)
}
func (m *GetMediaListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMediaListRequest.Merge(m, src)
}
func (m *GetMediaListRequest) XXX_Size() int {
	return xxx_messageInfo_GetMediaListRequest.Size(m)
}
func (m *GetMediaListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMediaListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMediaListRequest proto.InternalMessageInfo

func (m *GetMediaListRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetMediaListResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMediaListResponse) Reset()         { *m = GetMediaListResponse{} }
func (m *GetMediaListResponse) String() string { return proto.CompactTextString(m) }
func (*GetMediaListResponse) ProtoMessage()    {}
func (*GetMediaListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{1}
}

func (m *GetMediaListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMediaListResponse.Unmarshal(m, b)
}
func (m *GetMediaListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMediaListResponse.Marshal(b, m, deterministic)
}
func (m *GetMediaListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMediaListResponse.Merge(m, src)
}
func (m *GetMediaListResponse) XXX_Size() int {
	return xxx_messageInfo_GetMediaListResponse.Size(m)
}
func (m *GetMediaListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMediaListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMediaListResponse proto.InternalMessageInfo

func (m *GetMediaListResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SetMenuRequest struct {
	JsonMenu             string   `protobuf:"bytes,1,opt,name=jsonMenu,proto3" json:"jsonMenu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMenuRequest) Reset()         { *m = SetMenuRequest{} }
func (m *SetMenuRequest) String() string { return proto.CompactTextString(m) }
func (*SetMenuRequest) ProtoMessage()    {}
func (*SetMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{2}
}

func (m *SetMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMenuRequest.Unmarshal(m, b)
}
func (m *SetMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMenuRequest.Marshal(b, m, deterministic)
}
func (m *SetMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMenuRequest.Merge(m, src)
}
func (m *SetMenuRequest) XXX_Size() int {
	return xxx_messageInfo_SetMenuRequest.Size(m)
}
func (m *SetMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMenuRequest proto.InternalMessageInfo

func (m *SetMenuRequest) GetJsonMenu() string {
	if m != nil {
		return m.JsonMenu
	}
	return ""
}

type SetMenuResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMenuResponse) Reset()         { *m = SetMenuResponse{} }
func (m *SetMenuResponse) String() string { return proto.CompactTextString(m) }
func (*SetMenuResponse) ProtoMessage()    {}
func (*SetMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{3}
}

func (m *SetMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMenuResponse.Unmarshal(m, b)
}
func (m *SetMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMenuResponse.Marshal(b, m, deterministic)
}
func (m *SetMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMenuResponse.Merge(m, src)
}
func (m *SetMenuResponse) XXX_Size() int {
	return xxx_messageInfo_SetMenuResponse.Size(m)
}
func (m *SetMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMenuResponse proto.InternalMessageInfo

func (m *SetMenuResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SendTplMessageRequest struct {
	Openid               string                     `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	Tpl                  string                     `protobuf:"bytes,2,opt,name=tpl,proto3" json:"tpl,omitempty"`
	Data                 map[string]*TplMessageItem `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Url                  string                     `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Color                string                     `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	MiniProgram          *MiniProgram               `protobuf:"bytes,6,opt,name=miniProgram,proto3" json:"miniProgram,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SendTplMessageRequest) Reset()         { *m = SendTplMessageRequest{} }
func (m *SendTplMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendTplMessageRequest) ProtoMessage()    {}
func (*SendTplMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{4}
}

func (m *SendTplMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTplMessageRequest.Unmarshal(m, b)
}
func (m *SendTplMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTplMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendTplMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTplMessageRequest.Merge(m, src)
}
func (m *SendTplMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendTplMessageRequest.Size(m)
}
func (m *SendTplMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTplMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTplMessageRequest proto.InternalMessageInfo

func (m *SendTplMessageRequest) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *SendTplMessageRequest) GetTpl() string {
	if m != nil {
		return m.Tpl
	}
	return ""
}

func (m *SendTplMessageRequest) GetData() map[string]*TplMessageItem {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SendTplMessageRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SendTplMessageRequest) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *SendTplMessageRequest) GetMiniProgram() *MiniProgram {
	if m != nil {
		return m.MiniProgram
	}
	return nil
}

type MiniProgram struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	PagePath             string   `protobuf:"bytes,2,opt,name=pagePath,proto3" json:"pagePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiniProgram) Reset()         { *m = MiniProgram{} }
func (m *MiniProgram) String() string { return proto.CompactTextString(m) }
func (*MiniProgram) ProtoMessage()    {}
func (*MiniProgram) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{5}
}

func (m *MiniProgram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiniProgram.Unmarshal(m, b)
}
func (m *MiniProgram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiniProgram.Marshal(b, m, deterministic)
}
func (m *MiniProgram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiniProgram.Merge(m, src)
}
func (m *MiniProgram) XXX_Size() int {
	return xxx_messageInfo_MiniProgram.Size(m)
}
func (m *MiniProgram) XXX_DiscardUnknown() {
	xxx_messageInfo_MiniProgram.DiscardUnknown(m)
}

var xxx_messageInfo_MiniProgram proto.InternalMessageInfo

func (m *MiniProgram) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *MiniProgram) GetPagePath() string {
	if m != nil {
		return m.PagePath
	}
	return ""
}

type TplMessageItem struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Color                string   `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TplMessageItem) Reset()         { *m = TplMessageItem{} }
func (m *TplMessageItem) String() string { return proto.CompactTextString(m) }
func (*TplMessageItem) ProtoMessage()    {}
func (*TplMessageItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{6}
}

func (m *TplMessageItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TplMessageItem.Unmarshal(m, b)
}
func (m *TplMessageItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TplMessageItem.Marshal(b, m, deterministic)
}
func (m *TplMessageItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TplMessageItem.Merge(m, src)
}
func (m *TplMessageItem) XXX_Size() int {
	return xxx_messageInfo_TplMessageItem.Size(m)
}
func (m *TplMessageItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TplMessageItem.DiscardUnknown(m)
}

var xxx_messageInfo_TplMessageItem proto.InternalMessageInfo

func (m *TplMessageItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TplMessageItem) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

type SendTplMessageResponse struct {
	MsgID                int64    `protobuf:"varint,1,opt,name=msgID,proto3" json:"msgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTplMessageResponse) Reset()         { *m = SendTplMessageResponse{} }
func (m *SendTplMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendTplMessageResponse) ProtoMessage()    {}
func (*SendTplMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{7}
}

func (m *SendTplMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTplMessageResponse.Unmarshal(m, b)
}
func (m *SendTplMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTplMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendTplMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTplMessageResponse.Merge(m, src)
}
func (m *SendTplMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendTplMessageResponse.Size(m)
}
func (m *SendTplMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTplMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendTplMessageResponse proto.InternalMessageInfo

func (m *SendTplMessageResponse) GetMsgID() int64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

type SendMiniprogramMessageRequest struct {
	Openid               string                                `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	Tpl                  string                                `protobuf:"bytes,2,opt,name=tpl,proto3" json:"tpl,omitempty"`
	Page                 string                                `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	Data                 map[string]*MiniprogramTplMessageItem `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MiniprogramState     string                                `protobuf:"bytes,5,opt,name=miniprogramState,proto3" json:"miniprogramState,omitempty"`
	Lange                string                                `protobuf:"bytes,6,opt,name=lange,proto3" json:"lange,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *SendMiniprogramMessageRequest) Reset()         { *m = SendMiniprogramMessageRequest{} }
func (m *SendMiniprogramMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMiniprogramMessageRequest) ProtoMessage()    {}
func (*SendMiniprogramMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{8}
}

func (m *SendMiniprogramMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMiniprogramMessageRequest.Unmarshal(m, b)
}
func (m *SendMiniprogramMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMiniprogramMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMiniprogramMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMiniprogramMessageRequest.Merge(m, src)
}
func (m *SendMiniprogramMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMiniprogramMessageRequest.Size(m)
}
func (m *SendMiniprogramMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMiniprogramMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMiniprogramMessageRequest proto.InternalMessageInfo

func (m *SendMiniprogramMessageRequest) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *SendMiniprogramMessageRequest) GetTpl() string {
	if m != nil {
		return m.Tpl
	}
	return ""
}

func (m *SendMiniprogramMessageRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *SendMiniprogramMessageRequest) GetData() map[string]*MiniprogramTplMessageItem {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SendMiniprogramMessageRequest) GetMiniprogramState() string {
	if m != nil {
		return m.MiniprogramState
	}
	return ""
}

func (m *SendMiniprogramMessageRequest) GetLange() string {
	if m != nil {
		return m.Lange
	}
	return ""
}

type MiniprogramTplMessageItem struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiniprogramTplMessageItem) Reset()         { *m = MiniprogramTplMessageItem{} }
func (m *MiniprogramTplMessageItem) String() string { return proto.CompactTextString(m) }
func (*MiniprogramTplMessageItem) ProtoMessage()    {}
func (*MiniprogramTplMessageItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{9}
}

func (m *MiniprogramTplMessageItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiniprogramTplMessageItem.Unmarshal(m, b)
}
func (m *MiniprogramTplMessageItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiniprogramTplMessageItem.Marshal(b, m, deterministic)
}
func (m *MiniprogramTplMessageItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiniprogramTplMessageItem.Merge(m, src)
}
func (m *MiniprogramTplMessageItem) XXX_Size() int {
	return xxx_messageInfo_MiniprogramTplMessageItem.Size(m)
}
func (m *MiniprogramTplMessageItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MiniprogramTplMessageItem.DiscardUnknown(m)
}

var xxx_messageInfo_MiniprogramTplMessageItem proto.InternalMessageInfo

func (m *MiniprogramTplMessageItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SendMiniprogramMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMiniprogramMessageResponse) Reset()         { *m = SendMiniprogramMessageResponse{} }
func (m *SendMiniprogramMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMiniprogramMessageResponse) ProtoMessage()    {}
func (*SendMiniprogramMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e74b134486e7456c, []int{10}
}

func (m *SendMiniprogramMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMiniprogramMessageResponse.Unmarshal(m, b)
}
func (m *SendMiniprogramMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMiniprogramMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMiniprogramMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMiniprogramMessageResponse.Merge(m, src)
}
func (m *SendMiniprogramMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMiniprogramMessageResponse.Size(m)
}
func (m *SendMiniprogramMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMiniprogramMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMiniprogramMessageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetMediaListRequest)(nil), "wechat.GetMediaListRequest")
	proto.RegisterType((*GetMediaListResponse)(nil), "wechat.GetMediaListResponse")
	proto.RegisterType((*SetMenuRequest)(nil), "wechat.SetMenuRequest")
	proto.RegisterType((*SetMenuResponse)(nil), "wechat.SetMenuResponse")
	proto.RegisterType((*SendTplMessageRequest)(nil), "wechat.SendTplMessageRequest")
	proto.RegisterMapType((map[string]*TplMessageItem)(nil), "wechat.SendTplMessageRequest.DataEntry")
	proto.RegisterType((*MiniProgram)(nil), "wechat.MiniProgram")
	proto.RegisterType((*TplMessageItem)(nil), "wechat.TplMessageItem")
	proto.RegisterType((*SendTplMessageResponse)(nil), "wechat.SendTplMessageResponse")
	proto.RegisterType((*SendMiniprogramMessageRequest)(nil), "wechat.SendMiniprogramMessageRequest")
	proto.RegisterMapType((map[string]*MiniprogramTplMessageItem)(nil), "wechat.SendMiniprogramMessageRequest.DataEntry")
	proto.RegisterType((*MiniprogramTplMessageItem)(nil), "wechat.MiniprogramTplMessageItem")
	proto.RegisterType((*SendMiniprogramMessageResponse)(nil), "wechat.SendMiniprogramMessageResponse")
}

func init() {
	proto.RegisterFile("wechat.proto", fileDescriptor_e74b134486e7456c)
}

var fileDescriptor_e74b134486e7456c = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x55, 0xec, 0x24, 0x34, 0x93, 0x2a, 0x44, 0xdb, 0x10, 0x8c, 0xa1, 0x55, 0xba, 0x12, 0x10,
	0xaa, 0x2a, 0x15, 0x41, 0x08, 0x54, 0x90, 0x90, 0xa0, 0x08, 0x45, 0x22, 0x6a, 0xe5, 0xf0, 0xd4,
	0xb7, 0x6d, 0xb2, 0x72, 0x4d, 0x6c, 0xef, 0x62, 0x6f, 0x8a, 0xf2, 0x53, 0x7c, 0x03, 0x4f, 0x7c,
	0x17, 0xda, 0x8b, 0x63, 0x87, 0xc4, 0x05, 0xf1, 0x36, 0x33, 0x3e, 0x7b, 0xe6, 0x72, 0xc6, 0x03,
	0xbb, 0xdf, 0xe9, 0xf4, 0x9a, 0x88, 0x01, 0x4f, 0x98, 0x60, 0xa8, 0xae, 0x3d, 0xfc, 0x0c, 0xf6,
	0x3e, 0x51, 0x31, 0xa6, 0xb3, 0x80, 0x7c, 0x0e, 0x52, 0xe1, 0xd1, 0x6f, 0x0b, 0x9a, 0x0a, 0x84,
	0xa0, 0x2a, 0x96, 0x9c, 0x3a, 0x95, 0x5e, 0xa5, 0xdf, 0xf0, 0x94, 0x8d, 0x8f, 0xa0, 0xb3, 0x0e,
	0x4d, 0x39, 0x8b, 0x53, 0x2a, 0xb1, 0x33, 0x22, 0x48, 0x86, 0x95, 0x36, 0x3e, 0x86, 0xd6, 0x44,
	0x62, 0xe3, 0x45, 0xc6, 0xe8, 0xc2, 0xce, 0xd7, 0x94, 0xc5, 0x32, 0x64, 0x90, 0x2b, 0x1f, 0x1f,
	0xc2, 0xdd, 0x15, 0xda, 0x90, 0xb6, 0xc0, 0x62, 0x73, 0x05, 0xdc, 0xf1, 0x2c, 0x36, 0xc7, 0x3f,
	0x2c, 0xb8, 0x37, 0xa1, 0xf1, 0xec, 0x0b, 0x0f, 0xc7, 0x34, 0x4d, 0x89, 0x4f, 0x33, 0xe2, 0x2e,
	0xd4, 0x19, 0xa7, 0x71, 0x30, 0x33, 0xb4, 0xc6, 0x43, 0x6d, 0xb0, 0x05, 0x0f, 0x1d, 0x4b, 0x05,
	0xa5, 0x89, 0xde, 0x98, 0x42, 0xed, 0x9e, 0xdd, 0x6f, 0x0e, 0x9f, 0x0e, 0xcc, 0x40, 0xb6, 0xd2,
	0x0e, 0xce, 0x88, 0x20, 0x1f, 0x63, 0x91, 0x2c, 0x75, 0x47, 0x92, 0x6e, 0x91, 0x84, 0x4e, 0x55,
	0xd3, 0x2d, 0x92, 0x10, 0x75, 0xa0, 0x36, 0x65, 0x21, 0x4b, 0x9c, 0x9a, 0x8a, 0x69, 0x07, 0xbd,
	0x84, 0x66, 0x14, 0xc4, 0xc1, 0x45, 0xc2, 0xfc, 0x84, 0x44, 0x4e, 0xbd, 0x57, 0xe9, 0x37, 0x87,
	0x7b, 0x59, 0xae, 0x71, 0xfe, 0xc9, 0x2b, 0xe2, 0xdc, 0x73, 0x68, 0xac, 0x32, 0xca, 0x5c, 0x73,
	0xba, 0x34, 0xfd, 0x48, 0x13, 0x1d, 0x43, 0xed, 0x86, 0x84, 0x0b, 0xaa, 0xda, 0x69, 0x0e, 0xbb,
	0x19, 0x5f, 0x5e, 0xf7, 0x48, 0xd0, 0xc8, 0xd3, 0xa0, 0x53, 0xeb, 0x75, 0x05, 0xbf, 0x83, 0x66,
	0x21, 0x99, 0x2c, 0x96, 0x70, 0xbe, 0x1a, 0x92, 0x76, 0xa4, 0x28, 0x9c, 0xf8, 0xf4, 0x82, 0x88,
	0x6b, 0x33, 0xa8, 0x95, 0x8f, 0xdf, 0x42, 0x6b, 0x9d, 0x5d, 0x72, 0xe8, 0x22, 0x0c, 0x87, 0x72,
	0xf2, 0x31, 0x58, 0x85, 0x31, 0xe0, 0x01, 0x74, 0xff, 0x9c, 0xab, 0x51, 0xb6, 0x03, 0xb5, 0x28,
	0xf5, 0x47, 0x67, 0x8a, 0xc5, 0xf6, 0xb4, 0x83, 0x7f, 0x5a, 0xb0, 0x2f, 0x1f, 0xc8, 0x9a, 0xb9,
	0xae, 0xf9, 0xbf, 0x75, 0x46, 0x50, 0x95, 0x5d, 0x38, 0xb6, 0x5e, 0x48, 0x69, 0xa3, 0x0f, 0x46,
	0xfb, 0xaa, 0xd2, 0xfe, 0xa4, 0xa8, 0x7d, 0x69, 0xca, 0x8d, 0x1d, 0x38, 0x82, 0x76, 0x94, 0x83,
	0x27, 0x82, 0x08, 0x6a, 0xc4, 0xdf, 0x88, 0xcb, 0x36, 0x43, 0x12, 0xfb, 0x54, 0x6d, 0x40, 0xc3,
	0xd3, 0x8e, 0x7b, 0x79, 0xbb, 0xcc, 0xaf, 0xd6, 0x65, 0x3e, 0x2c, 0xae, 0x8d, 0x61, 0x2f, 0x57,
	0xfc, 0x39, 0x3c, 0x28, 0xc5, 0x6d, 0xd7, 0x0e, 0xf7, 0xe0, 0xa0, 0x6c, 0x02, 0x5a, 0xad, 0xe1,
	0x2f, 0x0b, 0xec, 0x34, 0xb9, 0x41, 0xe7, 0xf2, 0x87, 0x2e, 0xea, 0x89, 0xf6, 0x6f, 0xfd, 0x7f,
	0xdc, 0x83, 0xb2, 0xcf, 0x66, 0x0d, 0x7c, 0xbd, 0x20, 0x9b, 0xa9, 0xd1, 0xe3, 0x7f, 0x12, 0xc7,
	0x7d, 0xf2, 0x37, 0x98, 0x49, 0x74, 0x0a, 0x77, 0xcc, 0x71, 0x41, 0xdd, 0xfc, 0x49, 0xf1, 0x36,
	0xb9, 0xf7, 0x37, 0xe2, 0xe6, 0xed, 0x08, 0x76, 0x8b, 0x27, 0x0f, 0x3d, 0xcc, 0x80, 0x5b, 0x6e,
	0xa6, 0xfb, 0x68, 0xfb, 0x47, 0x4d, 0xf5, 0xbe, 0x7d, 0xd9, 0x8a, 0x82, 0x69, 0xc2, 0x4e, 0x34,
	0x88, 0x5f, 0x5d, 0xd5, 0xd5, 0x25, 0x7e, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x33, 0x4f,
	0xef, 0x99, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SrvClient is the client API for Srv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SrvClient interface {
	SendTplMessage(ctx context.Context, in *SendTplMessageRequest, opts ...grpc.CallOption) (*SendTplMessageResponse, error)
	SendMiniprogramMessage(ctx context.Context, in *SendMiniprogramMessageRequest, opts ...grpc.CallOption) (*SendMiniprogramMessageResponse, error)
	SetMenu(ctx context.Context, in *SetMenuRequest, opts ...grpc.CallOption) (*SetMenuResponse, error)
	GetMediaList(ctx context.Context, in *GetMediaListRequest, opts ...grpc.CallOption) (*GetMediaListResponse, error)
}

type srvClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvClient(cc grpc.ClientConnInterface) SrvClient {
	return &srvClient{cc}
}

func (c *srvClient) SendTplMessage(ctx context.Context, in *SendTplMessageRequest, opts ...grpc.CallOption) (*SendTplMessageResponse, error) {
	out := new(SendTplMessageResponse)
	err := c.cc.Invoke(ctx, "/wechat.srv/SendTplMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvClient) SendMiniprogramMessage(ctx context.Context, in *SendMiniprogramMessageRequest, opts ...grpc.CallOption) (*SendMiniprogramMessageResponse, error) {
	out := new(SendMiniprogramMessageResponse)
	err := c.cc.Invoke(ctx, "/wechat.srv/SendMiniprogramMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvClient) SetMenu(ctx context.Context, in *SetMenuRequest, opts ...grpc.CallOption) (*SetMenuResponse, error) {
	out := new(SetMenuResponse)
	err := c.cc.Invoke(ctx, "/wechat.srv/SetMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvClient) GetMediaList(ctx context.Context, in *GetMediaListRequest, opts ...grpc.CallOption) (*GetMediaListResponse, error) {
	out := new(GetMediaListResponse)
	err := c.cc.Invoke(ctx, "/wechat.srv/GetMediaList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvServer is the server API for Srv service.
type SrvServer interface {
	SendTplMessage(context.Context, *SendTplMessageRequest) (*SendTplMessageResponse, error)
	SendMiniprogramMessage(context.Context, *SendMiniprogramMessageRequest) (*SendMiniprogramMessageResponse, error)
	SetMenu(context.Context, *SetMenuRequest) (*SetMenuResponse, error)
	GetMediaList(context.Context, *GetMediaListRequest) (*GetMediaListResponse, error)
}

// UnimplementedSrvServer can be embedded to have forward compatible implementations.
type UnimplementedSrvServer struct {
}

func (*UnimplementedSrvServer) SendTplMessage(ctx context.Context, req *SendTplMessageRequest) (*SendTplMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTplMessage not implemented")
}
func (*UnimplementedSrvServer) SendMiniprogramMessage(ctx context.Context, req *SendMiniprogramMessageRequest) (*SendMiniprogramMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMiniprogramMessage not implemented")
}
func (*UnimplementedSrvServer) SetMenu(ctx context.Context, req *SetMenuRequest) (*SetMenuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMenu not implemented")
}
func (*UnimplementedSrvServer) GetMediaList(ctx context.Context, req *GetMediaListRequest) (*GetMediaListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaList not implemented")
}

func RegisterSrvServer(s *grpc.Server, srv SrvServer) {
	s.RegisterService(&_Srv_serviceDesc, srv)
}

func _Srv_SendTplMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTplMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvServer).SendTplMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat.srv/SendTplMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvServer).SendTplMessage(ctx, req.(*SendTplMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Srv_SendMiniprogramMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMiniprogramMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvServer).SendMiniprogramMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat.srv/SendMiniprogramMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvServer).SendMiniprogramMessage(ctx, req.(*SendMiniprogramMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Srv_SetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvServer).SetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat.srv/SetMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvServer).SetMenu(ctx, req.(*SetMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Srv_GetMediaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvServer).GetMediaList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat.srv/GetMediaList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvServer).GetMediaList(ctx, req.(*GetMediaListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Srv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wechat.srv",
	HandlerType: (*SrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTplMessage",
			Handler:    _Srv_SendTplMessage_Handler,
		},
		{
			MethodName: "SendMiniprogramMessage",
			Handler:    _Srv_SendMiniprogramMessage_Handler,
		},
		{
			MethodName: "SetMenu",
			Handler:    _Srv_SetMenu_Handler,
		},
		{
			MethodName: "GetMediaList",
			Handler:    _Srv_GetMediaList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wechat.proto",
}
