// protoc --go_out=plugins=grpc:. ./spacegrower/meta/spacegrower.meta.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: spacegrower/meta/spacegrower.meta.proto

package meta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServiceMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetServiceMetaRequest) Reset() {
	*x = GetServiceMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServiceMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceMetaRequest) ProtoMessage() {}

func (x *GetServiceMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceMetaRequest.ProtoReflect.Descriptor instead.
func (*GetServiceMetaRequest) Descriptor() ([]byte, []int) {
	return file_spacegrower_meta_spacegrower_meta_proto_rawDescGZIP(), []int{0}
}

type GetServiceMetaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta map[string][]byte `protobuf:"bytes,1,rep,name=Meta,proto3" json:"Meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetServiceMetaReply) Reset() {
	*x = GetServiceMetaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServiceMetaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceMetaReply) ProtoMessage() {}

func (x *GetServiceMetaReply) ProtoReflect() protoreflect.Message {
	mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceMetaReply.ProtoReflect.Descriptor instead.
func (*GetServiceMetaReply) Descriptor() ([]byte, []int) {
	return file_spacegrower_meta_spacegrower_meta_proto_rawDescGZIP(), []int{1}
}

func (x *GetServiceMetaReply) GetMeta() map[string][]byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetServiceConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=Region,proto3" json:"Region,omitempty"`
	File   string `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
}

func (x *GetServiceConfigRequest) Reset() {
	*x = GetServiceConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServiceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceConfigRequest) ProtoMessage() {}

func (x *GetServiceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceConfigRequest.ProtoReflect.Descriptor instead.
func (*GetServiceConfigRequest) Descriptor() ([]byte, []int) {
	return file_spacegrower_meta_spacegrower_meta_proto_rawDescGZIP(), []int{2}
}

func (x *GetServiceConfigRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetServiceConfigRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type GetServiceConfigReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File    string `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *GetServiceConfigReply) Reset() {
	*x = GetServiceConfigReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServiceConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceConfigReply) ProtoMessage() {}

func (x *GetServiceConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceConfigReply.ProtoReflect.Descriptor instead.
func (*GetServiceConfigReply) Descriptor() ([]byte, []int) {
	return file_spacegrower_meta_spacegrower_meta_proto_rawDescGZIP(), []int{3}
}

func (x *GetServiceConfigReply) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *GetServiceConfigReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GenerateJWTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   string            `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Fields map[string]string `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GenerateJWTRequest) Reset() {
	*x = GenerateJWTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateJWTRequest) ProtoMessage() {}

func (x *GenerateJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateJWTRequest.ProtoReflect.Descriptor instead.
func (*GenerateJWTRequest) Descriptor() ([]byte, []int) {
	return file_spacegrower_meta_spacegrower_meta_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateJWTRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GenerateJWTRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GenerateJWTReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT        string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	ExpireTime int64  `protobuf:"varint,2,opt,name=ExpireTime,proto3" json:"ExpireTime,omitempty"`
}

func (x *GenerateJWTReply) Reset() {
	*x = GenerateJWTReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateJWTReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateJWTReply) ProtoMessage() {}

func (x *GenerateJWTReply) ProtoReflect() protoreflect.Message {
	mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateJWTReply.ProtoReflect.Descriptor instead.
func (*GenerateJWTReply) Descriptor() ([]byte, []int) {
	return file_spacegrower_meta_spacegrower_meta_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateJWTReply) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *GenerateJWTReply) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type GetServiceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid string `protobuf:"bytes,1,opt,name=Appid,proto3" json:"Appid,omitempty"`
}

func (x *GetServiceInfoRequest) Reset() {
	*x = GetServiceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServiceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoRequest) ProtoMessage() {}

func (x *GetServiceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServiceInfoRequest) Descriptor() ([]byte, []int) {
	return file_spacegrower_meta_spacegrower_meta_proto_rawDescGZIP(), []int{6}
}

func (x *GetServiceInfoRequest) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

type GetServiceAuthorityInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid       string `protobuf:"bytes,1,opt,name=Appid,proto3" json:"Appid,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Status      int32  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Secret      string `protobuf:"bytes,5,opt,name=Secret,proto3" json:"Secret,omitempty"`
	Namespace   string `protobuf:"bytes,6,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	OrgID       string `protobuf:"bytes,7,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
}

func (x *GetServiceAuthorityInfoReply) Reset() {
	*x = GetServiceAuthorityInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServiceAuthorityInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceAuthorityInfoReply) ProtoMessage() {}

func (x *GetServiceAuthorityInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_spacegrower_meta_spacegrower_meta_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceAuthorityInfoReply.ProtoReflect.Descriptor instead.
func (*GetServiceAuthorityInfoReply) Descriptor() ([]byte, []int) {
	return file_spacegrower_meta_spacegrower_meta_proto_rawDescGZIP(), []int{7}
}

func (x *GetServiceAuthorityInfoReply) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *GetServiceAuthorityInfoReply) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetServiceAuthorityInfoReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetServiceAuthorityInfoReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetServiceAuthorityInfoReply) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GetServiceAuthorityInfoReply) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetServiceAuthorityInfoReply) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

var File_spacegrower_meta_spacegrower_meta_proto protoreflect.FileDescriptor

var file_spacegrower_meta_spacegrower_meta_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x70, 0x61, 0x63, 0x65, 0x67, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x2f, 0x6d, 0x65,
	0x74, 0x61, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x67, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x38, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x4d,
	0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x45, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x45, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4a,
	0x57, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x3d, 0x0a,
	0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4a, 0x57,
	0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x39, 0x0a, 0x0b,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x44, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x4a,
	0x57, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x1e, 0x0a,
	0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2d, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x69, 0x64, 0x22, 0xd0, 0x01, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x41, 0x70, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70,
	0x70, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72, 0x67,
	0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x72, 0x67, 0x49, 0x44, 0x32,
	0xcd, 0x02, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x43, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x12, 0x19, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5e, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x52, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x1e, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x4c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x12, 0x1c, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x12, 0x5a, 0x10, 0x73, 0x70, 0x61, 0x63, 0x65, 0x67, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spacegrower_meta_spacegrower_meta_proto_rawDescOnce sync.Once
	file_spacegrower_meta_spacegrower_meta_proto_rawDescData = file_spacegrower_meta_spacegrower_meta_proto_rawDesc
)

func file_spacegrower_meta_spacegrower_meta_proto_rawDescGZIP() []byte {
	file_spacegrower_meta_spacegrower_meta_proto_rawDescOnce.Do(func() {
		file_spacegrower_meta_spacegrower_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_spacegrower_meta_spacegrower_meta_proto_rawDescData)
	})
	return file_spacegrower_meta_spacegrower_meta_proto_rawDescData
}

var file_spacegrower_meta_spacegrower_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_spacegrower_meta_spacegrower_meta_proto_goTypes = []interface{}{
	(*GetServiceMetaRequest)(nil),        // 0: space.GetServiceMetaRequest
	(*GetServiceMetaReply)(nil),          // 1: space.GetServiceMetaReply
	(*GetServiceConfigRequest)(nil),      // 2: space.GetServiceConfigRequest
	(*GetServiceConfigReply)(nil),        // 3: space.GetServiceConfigReply
	(*GenerateJWTRequest)(nil),           // 4: space.GenerateJWTRequest
	(*GenerateJWTReply)(nil),             // 5: space.GenerateJWTReply
	(*GetServiceInfoRequest)(nil),        // 6: space.GetServiceInfoRequest
	(*GetServiceAuthorityInfoReply)(nil), // 7: space.GetServiceAuthorityInfoReply
	nil,                                  // 8: space.GetServiceMetaReply.MetaEntry
	nil,                                  // 9: space.GenerateJWTRequest.FieldsEntry
}
var file_spacegrower_meta_spacegrower_meta_proto_depIdxs = []int32{
	8, // 0: space.GetServiceMetaReply.Meta:type_name -> space.GetServiceMetaReply.MetaEntry
	9, // 1: space.GenerateJWTRequest.Fields:type_name -> space.GenerateJWTRequest.FieldsEntry
	4, // 2: space.Meta.GenerateJWT:input_type -> space.GenerateJWTRequest
	6, // 3: space.Meta.GetServiceAuthorityInfo:input_type -> space.GetServiceInfoRequest
	2, // 4: space.Meta.GetServiceConfig:input_type -> space.GetServiceConfigRequest
	0, // 5: space.Meta.GetServiceMeta:input_type -> space.GetServiceMetaRequest
	5, // 6: space.Meta.GenerateJWT:output_type -> space.GenerateJWTReply
	7, // 7: space.Meta.GetServiceAuthorityInfo:output_type -> space.GetServiceAuthorityInfoReply
	3, // 8: space.Meta.GetServiceConfig:output_type -> space.GetServiceConfigReply
	1, // 9: space.Meta.GetServiceMeta:output_type -> space.GetServiceMetaReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spacegrower_meta_spacegrower_meta_proto_init() }
func file_spacegrower_meta_spacegrower_meta_proto_init() {
	if File_spacegrower_meta_spacegrower_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spacegrower_meta_spacegrower_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServiceMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacegrower_meta_spacegrower_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServiceMetaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacegrower_meta_spacegrower_meta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServiceConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacegrower_meta_spacegrower_meta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServiceConfigReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacegrower_meta_spacegrower_meta_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateJWTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacegrower_meta_spacegrower_meta_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateJWTReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacegrower_meta_spacegrower_meta_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServiceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spacegrower_meta_spacegrower_meta_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServiceAuthorityInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spacegrower_meta_spacegrower_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spacegrower_meta_spacegrower_meta_proto_goTypes,
		DependencyIndexes: file_spacegrower_meta_spacegrower_meta_proto_depIdxs,
		MessageInfos:      file_spacegrower_meta_spacegrower_meta_proto_msgTypes,
	}.Build()
	File_spacegrower_meta_spacegrower_meta_proto = out.File
	file_spacegrower_meta_spacegrower_meta_proto_rawDesc = nil
	file_spacegrower_meta_spacegrower_meta_proto_goTypes = nil
	file_spacegrower_meta_spacegrower_meta_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MetaClient is the client API for Meta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaClient interface {
	GenerateJWT(ctx context.Context, in *GenerateJWTRequest, opts ...grpc.CallOption) (*GenerateJWTReply, error)
	GetServiceAuthorityInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceAuthorityInfoReply, error)
	GetServiceConfig(ctx context.Context, in *GetServiceConfigRequest, opts ...grpc.CallOption) (*GetServiceConfigReply, error)
	GetServiceMeta(ctx context.Context, in *GetServiceMetaRequest, opts ...grpc.CallOption) (*GetServiceMetaReply, error)
}

type metaClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaClient(cc grpc.ClientConnInterface) MetaClient {
	return &metaClient{cc}
}

func (c *metaClient) GenerateJWT(ctx context.Context, in *GenerateJWTRequest, opts ...grpc.CallOption) (*GenerateJWTReply, error) {
	out := new(GenerateJWTReply)
	err := c.cc.Invoke(ctx, "/space.Meta/GenerateJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) GetServiceAuthorityInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceAuthorityInfoReply, error) {
	out := new(GetServiceAuthorityInfoReply)
	err := c.cc.Invoke(ctx, "/space.Meta/GetServiceAuthorityInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) GetServiceConfig(ctx context.Context, in *GetServiceConfigRequest, opts ...grpc.CallOption) (*GetServiceConfigReply, error) {
	out := new(GetServiceConfigReply)
	err := c.cc.Invoke(ctx, "/space.Meta/GetServiceConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaClient) GetServiceMeta(ctx context.Context, in *GetServiceMetaRequest, opts ...grpc.CallOption) (*GetServiceMetaReply, error) {
	out := new(GetServiceMetaReply)
	err := c.cc.Invoke(ctx, "/space.Meta/GetServiceMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServer is the server API for Meta service.
type MetaServer interface {
	GenerateJWT(context.Context, *GenerateJWTRequest) (*GenerateJWTReply, error)
	GetServiceAuthorityInfo(context.Context, *GetServiceInfoRequest) (*GetServiceAuthorityInfoReply, error)
	GetServiceConfig(context.Context, *GetServiceConfigRequest) (*GetServiceConfigReply, error)
	GetServiceMeta(context.Context, *GetServiceMetaRequest) (*GetServiceMetaReply, error)
}

// UnimplementedMetaServer can be embedded to have forward compatible implementations.
type UnimplementedMetaServer struct {
}

func (*UnimplementedMetaServer) GenerateJWT(context.Context, *GenerateJWTRequest) (*GenerateJWTReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateJWT not implemented")
}
func (*UnimplementedMetaServer) GetServiceAuthorityInfo(context.Context, *GetServiceInfoRequest) (*GetServiceAuthorityInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceAuthorityInfo not implemented")
}
func (*UnimplementedMetaServer) GetServiceConfig(context.Context, *GetServiceConfigRequest) (*GetServiceConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceConfig not implemented")
}
func (*UnimplementedMetaServer) GetServiceMeta(context.Context, *GetServiceMetaRequest) (*GetServiceMetaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceMeta not implemented")
}

func RegisterMetaServer(s *grpc.Server, srv MetaServer) {
	s.RegisterService(&_Meta_serviceDesc, srv)
}

func _Meta_GenerateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).GenerateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/space.Meta/GenerateJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).GenerateJWT(ctx, req.(*GenerateJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_GetServiceAuthorityInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).GetServiceAuthorityInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/space.Meta/GetServiceAuthorityInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).GetServiceAuthorityInfo(ctx, req.(*GetServiceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_GetServiceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).GetServiceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/space.Meta/GetServiceConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).GetServiceConfig(ctx, req.(*GetServiceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meta_GetServiceMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServer).GetServiceMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/space.Meta/GetServiceMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServer).GetServiceMeta(ctx, req.(*GetServiceMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Meta_serviceDesc = grpc.ServiceDesc{
	ServiceName: "space.Meta",
	HandlerType: (*MetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateJWT",
			Handler:    _Meta_GenerateJWT_Handler,
		},
		{
			MethodName: "GetServiceAuthorityInfo",
			Handler:    _Meta_GetServiceAuthorityInfo_Handler,
		},
		{
			MethodName: "GetServiceConfig",
			Handler:    _Meta_GetServiceConfig_Handler,
		},
		{
			MethodName: "GetServiceMeta",
			Handler:    _Meta_GetServiceMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spacegrower/meta/spacegrower.meta.proto",
}
